version: '3'

services:
  db:
    image: mysql:9.1.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - .env.local
  web:
    depends_on:
      - "db"
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    env_file:
      - .env.local
